version: "3.8"

services:
  blockchain:
    image: trufflesuite/ganache
    command: >
      ganache
      --host 0.0.0.0
      --port 8545
      --deterministic
    ports:
      - "8545:8545"

  deployer:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - blockchain
    environment:
      RPC_URL: http://blockchain:8545
